In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("card_transdata.csv")
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

Cleaning the Dataset:

In [3]:
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [4]:
df_chip = df[df['used_chip'] == 1]
df_pin = df[df['used_pin_number'] == 1]

In [6]:
df_pin

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0,0.0
23,8.084177,0.138203,0.378661,1.0,0.0,1.0,0.0,0.0
37,202.757442,0.275015,0.775549,1.0,0.0,1.0,1.0,0.0
51,43.281314,3.367793,0.676058,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999906,10.397783,3.656735,3.556847,1.0,0.0,1.0,1.0,0.0
999915,3.202150,25.714337,1.023930,1.0,1.0,1.0,1.0,0.0
999937,31.590252,0.936689,2.157707,1.0,0.0,1.0,0.0,0.0
999971,5.131162,5.150362,2.261678,1.0,1.0,1.0,0.0,0.0
999973,10.148074,4.465290,12.022734,1.0,0.0,1.0,0.0,0.0

In [7]:
df_chip

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [8]:
df_pin.drop(columns=["used_chip", "used_pin_number"])
df_chip.drop(columns=["used_chip", "used_pin_number"])

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0
...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0

In [9]:
df_pin

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0,0.0
23,8.084177,0.138203,0.378661,1.0,0.0,1.0,0.0,0.0
37,202.757442,0.275015,0.775549,1.0,0.0,1.0,1.0,0.0
51,43.281314,3.367793,0.676058,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999906,10.397783,3.656735,3.556847,1.0,0.0,1.0,1.0,0.0
999915,3.202150,25.714337,1.023930,1.0,1.0,1.0,1.0,0.0
999937,31.590252,0.936689,2.157707,1.0,0.0,1.0,0.0,0.0
999971,5.131162,5.150362,2.261678,1.0,1.0,1.0,0.0,0.0
999973,10.148074,4.465290,12.022734,1.0,0.0,1.0,0.0,0.0

In [10]:
df_chip

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [12]:
df_chip_fraud = df_chip[df_chip['fraud'] == 1]
df_pin_fraud = df_pin[df_pin['fraud'] == 1]
df_chip_nofraud = df_chip[df_chip['fraud'] == 0]
df_pin_nofraud = df_pin[df_pin['fraud'] == 0]

In [13]:
df_chip_fraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
35,26.711462,1.552008,4.603601,1.0,1.0,0.0,1.0,1.0
268,5.764412,0.624542,8.565935,1.0,1.0,0.0,1.0,1.0
269,7.230067,4.029309,5.746112,1.0,1.0,0.0,1.0,1.0
292,24.337488,1.398618,6.230792,1.0,1.0,0.0,1.0,1.0
338,12.750895,0.857614,17.706145,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
999811,1.738038,0.134839,10.117408,0.0,1.0,0.0,1.0,1.0
999830,4.000970,0.095762,4.149602,1.0,1.0,0.0,1.0,1.0
999834,12.397805,7.300905,8.433401,1.0,1.0,0.0,1.0,1.0
999883,14.850909,7.218322,10.680334,1.0,1.0,0.0,1.0,1.0
999949,15.724799,1.875906,11.009366,1.0,1.0,0.0,1.0,1.0

In [14]:
df_pin_fraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
2642,223.038039,1.017896,7.041224,1.0,0.0,1.0,1.0,1.0
7383,6.167166,56.962256,7.240496,1.0,0.0,1.0,1.0,1.0
10943,392.369845,0.254992,5.832195,1.0,0.0,1.0,1.0,1.0
14192,383.472053,0.843807,5.611873,1.0,0.0,1.0,1.0,1.0
15374,2.069962,52.735588,8.160324,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
978665,532.135482,1.078814,45.406373,1.0,0.0,1.0,1.0,1.0
982478,110.129342,11.195667,4.254132,1.0,0.0,1.0,1.0,1.0
984884,111.529578,2.550624,15.138699,1.0,0.0,1.0,1.0,1.0
995256,406.633425,4.956463,7.912023,1.0,0.0,1.0,1.0,1.0
997283,6.732468,94.055969,7.712033,1.0,0.0,1.0,1.0,1.0

In [15]:
df_chip_nofraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [16]:
df_pin_nofraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0,0.0
23,8.084177,0.138203,0.378661,1.0,0.0,1.0,0.0,0.0
37,202.757442,0.275015,0.775549,1.0,0.0,1.0,1.0,0.0
51,43.281314,3.367793,0.676058,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999906,10.397783,3.656735,3.556847,1.0,0.0,1.0,1.0,0.0
999915,3.202150,25.714337,1.023930,1.0,1.0,1.0,1.0,0.0
999937,31.590252,0.936689,2.157707,1.0,0.0,1.0,0.0,0.0
999971,5.131162,5.150362,2.261678,1.0,1.0,1.0,0.0,0.0
999973,10.148074,4.465290,12.022734,1.0,0.0,1.0,0.0,0.0

In [17]:
df_chip_fraud.drop(columns=["fraud"])
df_pin_fraud.drop(columns=["fraud"])
df_chip_nofraud.drop(columns=["fraud"])
df_pin_nofraud.drop(columns=["fraud"])

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0
23,8.084177,0.138203,0.378661,1.0,0.0,1.0,0.0
37,202.757442,0.275015,0.775549,1.0,0.0,1.0,1.0
51,43.281314,3.367793,0.676058,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...
999906,10.397783,3.656735,3.556847,1.0,0.0,1.0,1.0
999915,3.202150,25.714337,1.023930,1.0,1.0,1.0,1.0
999937,31.590252,0.936689,2.157707,1.0,0.0,1.0,0.0
999971,5.131162,5.150362,2.261678,1.0,1.0,1.0,0.0
999973,10.148074,4.465290,12.022734,1.0,0.0,1.0,0.0

In [18]:
df_chip_fraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
35,26.711462,1.552008,4.603601,1.0,1.0,0.0,1.0,1.0
268,5.764412,0.624542,8.565935,1.0,1.0,0.0,1.0,1.0
269,7.230067,4.029309,5.746112,1.0,1.0,0.0,1.0,1.0
292,24.337488,1.398618,6.230792,1.0,1.0,0.0,1.0,1.0
338,12.750895,0.857614,17.706145,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
999811,1.738038,0.134839,10.117408,0.0,1.0,0.0,1.0,1.0
999830,4.000970,0.095762,4.149602,1.0,1.0,0.0,1.0,1.0
999834,12.397805,7.300905,8.433401,1.0,1.0,0.0,1.0,1.0
999883,14.850909,7.218322,10.680334,1.0,1.0,0.0,1.0,1.0
999949,15.724799,1.875906,11.009366,1.0,1.0,0.0,1.0,1.0

In [19]:
df_pin_fraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
2642,223.038039,1.017896,7.041224,1.0,0.0,1.0,1.0,1.0
7383,6.167166,56.962256,7.240496,1.0,0.0,1.0,1.0,1.0
10943,392.369845,0.254992,5.832195,1.0,0.0,1.0,1.0,1.0
14192,383.472053,0.843807,5.611873,1.0,0.0,1.0,1.0,1.0
15374,2.069962,52.735588,8.160324,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
978665,532.135482,1.078814,45.406373,1.0,0.0,1.0,1.0,1.0
982478,110.129342,11.195667,4.254132,1.0,0.0,1.0,1.0,1.0
984884,111.529578,2.550624,15.138699,1.0,0.0,1.0,1.0,1.0
995256,406.633425,4.956463,7.912023,1.0,0.0,1.0,1.0,1.0
997283,6.732468,94.055969,7.712033,1.0,0.0,1.0,1.0,1.0

In [20]:
df_chip_nofraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
11,13.592368,0.240540,1.370330,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [21]:
df_pin_nofraud

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
15,179.665148,0.120920,0.535640,1.0,1.0,1.0,1.0,0.0
23,8.084177,0.138203,0.378661,1.0,0.0,1.0,0.0,0.0
37,202.757442,0.275015,0.775549,1.0,0.0,1.0,1.0,0.0
51,43.281314,3.367793,0.676058,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999906,10.397783,3.656735,3.556847,1.0,0.0,1.0,1.0,0.0
999915,3.202150,25.714337,1.023930,1.0,1.0,1.0,1.0,0.0
999937,31.590252,0.936689,2.157707,1.0,0.0,1.0,0.0,0.0
999971,5.131162,5.150362,2.261678,1.0,1.0,1.0,0.0,0.0
999973,10.148074,4.465290,12.022734,1.0,0.0,1.0,0.0,0.0