In [4]:
import pandas as pd

In [6]:
df = pd.read_excel(io='~/Desktop/NeuedaGroup44/card_transdata.xlsx', sheet_name='card_transdata')

In [16]:
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0
1,10.829943,0.175592,1.294219,1,0,0,0,0
2,5.091079,0.805153,0.427715,1,0,0,1,0
3,2.247564,5.600044,0.362663,1,1,0,1,0
4,44.190936,0.566486,2.222767,1,1,0,1,0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0
999996,19.872726,2.683904,2.778303,1,1,0,0,0
999997,2.914857,1.472687,0.218075,1,1,0,1,0
999998,4.258729,0.242023,0.475822,1,0,0,1,0
999999,58.108125,0.318110,0.386920,1,1,0,1,0

In [26]:
df['big_dist'] = df['distance_from_home'] > 50
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist
0,57.877857,0.311140,1.945940,1,1,0,0,0,True
1,10.829943,0.175592,1.294219,1,0,0,0,0,False
2,5.091079,0.805153,0.427715,1,0,0,1,0,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False
...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True

In [30]:
df['is_fraud_big_dist'] = (df['big_dist'] is True) and (fraud == 1)
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,False
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False
...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False

In [32]:
df['is_fraud_small_dist'] = (df['big_dist'] is False) and (fraud == 1)
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_fraud,is_fraud_small_dist
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False,False
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,False,False
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,False,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,False,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False,False

In [36]:
df.drop(columns='is_fraud')

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_fraud_small_dist
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,False
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False
...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False

In [45]:
del df['is_fraud_small_dist']

In [46]:
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist
0,57.877857,0.311140,1.945940,1,1,0,0,0,True
1,10.829943,0.175592,1.294219,1,0,0,0,0,False
2,5.091079,0.805153,0.427715,1,0,0,1,0,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False
...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True

In [56]:
df['is_chip_fraud'] = (df['used_chip'] == 1) == (df['fraud'] == 1)
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_chip_fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,True
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,True
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False
...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,True
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False

In [59]:
df['is_pin_fraud'] = (df['used_pin_number'] == 1) == (df['fraud'] == 1)
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_chip_fraud,is_pin_fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False,True
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,True,True
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,True,True
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False,True
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False,True
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False,True
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False,True
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,True,True
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False,True

In [61]:
df['is_online_fraud'] = (df['online_order'] == 1) == (df['fraud'] == 1)
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud,big_dist,is_chip_fraud,is_pin_fraud,is_online_fraud
0,57.877857,0.311140,1.945940,1,1,0,0,0,True,False,True,True
1,10.829943,0.175592,1.294219,1,0,0,0,0,False,True,True,True
2,5.091079,0.805153,0.427715,1,0,0,1,0,False,True,True,False
3,2.247564,5.600044,0.362663,1,1,0,1,0,False,False,True,False
4,44.190936,0.566486,2.222767,1,1,0,1,0,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1,1,0,0,0,False,False,True,True
999996,19.872726,2.683904,2.778303,1,1,0,0,0,False,False,True,True
999997,2.914857,1.472687,0.218075,1,1,0,1,0,False,False,True,False
999998,4.258729,0.242023,0.475822,1,0,0,1,0,False,True,True,False
999999,58.108125,0.318110,0.386920,1,1,0,1,0,True,False,True,False

In [69]:
percent_fraud_online = (df['is_online_fraud'].sum()/df.shape[0]) * 100
print(percent_fraud_online)

42.7467

In [71]:
percent_fraud_chip = (df['is_chip_fraud'].sum()/df.shape[0]) * 100
print(percent_fraud_chip)

60.70179999999999

In [72]:
percent_fraud_pin = (df['is_pin_fraud'].sum()/df.shape[0]) * 100
print(percent_fraud_pin)

81.2535