In [1]:
#Start out with clearning dataet

#Show the dataframe

#Start with major percentages based on fraud/no fraud

#dive into card usage

#cond prob

#distance

#cross analysis

#For each section, flip back and forth with the tableau dashboard

In [5]:
#import atatements
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
#initially visualizing the dataset
df = pd.read_csv("card_transdata-checkpoint.csv")
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [9]:
#Cleaning out th rows containing NA/unwanted data entries
df = df.dropna(how='any')
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999998,4.258729,0.242023,0.475822,1.0,0.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [37]:
df = df[((df['used_chip'] == 1)&(df['used_pin_number'] == 0)) | ((df['used_chip'] == 0)&(df['used_pin_number'] == 1))]
df

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
7,4.848247,0.320735,1.273050,1.0,0.0,1.0,0.0,0.0
10,14.263530,0.158758,1.136102,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
999990,20.334489,11.437333,0.699527,1.0,1.0,0.0,1.0,0.0
999995,2.207101,0.112651,1.626798,1.0,1.0,0.0,0.0,0.0
999996,19.872726,2.683904,2.778303,1.0,1.0,0.0,0.0,0.0
999997,2.914857,1.472687,0.218075,1.0,1.0,0.0,1.0,0.0
999999,58.108125,0.318110,0.386920,1.0,1.0,0.0,1.0,0.0

In [39]:
len(df[(df['used_pin_number'] == 0) & (df['used_chip'] == 0)].index)

0

In [25]:
df_fraud = df[df['fraud'] == 1]
usedchip_fraudper = len(df_fraud[df_fraud['used_chip'] == 1].index)/len(df_fraud.index)
usedchip_fraudper * 100

25.639852178986995

In [24]:
usedpin_fraudper = len(df_fraud[df_fraud['used_pin_number'] == 1].index)/len(df_fraud.index)
usedpin_fraudper * 100

0.31234625813759254

In [35]:
other_fraudper = len(df_fraud[(df_fraud['used_pin_number'] == 0) & (df_fraud['used_chip'] == 0)].index)/len(df_fraud.index)
other_fraudper

0.7405809869226456